/* ============================================================
   CASO CERRADO — EL ESTADO DE LOS MUERTOS
   data.js · Todo el contenido extraído de "C 07 - LA NATURALEZA HUMANA"
   Para editar preguntas, modifica este archivo. Nada más.
   ============================================================ */

const VERSICULOS = [
  { id:"v1", ref:"Génesis 2:7",
    texto:"Entonces Jehová Dios formó al hombre del polvo de la tierra, y sopló en su nariz aliento de vida, y fue el hombre un alma viviente.",
    idea:"Polvo de la tierra + aliento de vida = alma viviente.",
    demuestra:"El alma no se le PUSO al hombre: el hombre LLEGÓ A SER un alma viviente al unirse cuerpo y espíritu.",
    clave:"Y FUE EL HOMBRE UN ALMA VIVIENTE",
    concepto:"Creación del ser humano",
    pregunta:"¿Con qué elementos creó Dios al hombre?" },
  { id:"v2", ref:"Ezequiel 18:4",
    texto:"He aquí que todas las almas son mías; como el alma del padre, así el alma del hijo es mía; el alma que pecare, esa morirá.",
    idea:"Todas las almas son de Dios. El alma que pecare, morirá.",
    demuestra:"Que el alma SÍ PUEDE MORIR. No es inmortal por sí misma.",
    clave:"EL ALMA QUE PECARE, ESA MORIRÁ",
    concepto:"El alma puede morir",
    pregunta:"¿Puede morir el alma?" },
  { id:"v3", ref:"Ezequiel 18:5-18",
    texto:"El justo vivirá. El que hiciere abominación, de cierto morirá. El hijo justo no morirá por la maldad de su padre; de cierto vivirá.",
    idea:"Cada quien responde por sus propios actos.",
    demuestra:"Que nadie muere por el pecado de otro.",
    clave:"NO MORIRÁ POR LA MALDAD DE SU PADRE",
    concepto:"Responsabilidad individual",
    pregunta:"¿Muere el hijo por el pecado del padre?" },
  { id:"v4", ref:"Eclesiastés 9:2",
    texto:"Todo acontece de la misma manera a todos; un mismo suceso ocurre al justo y al impío; al bueno, al limpio y al no limpio; como al bueno, así al que peca.",
    idea:"La muerte llega igual a todos.",
    demuestra:"Que el justo y el impío mueren de la misma manera.",
    clave:"UN MISMO SUCESO OCURRE A TODOS",
    concepto:"Estado de los muertos",
    pregunta:"¿El bueno y el malo mueren de la misma manera?" },
  { id:"v5", ref:"Eclesiastés 9:4",
    texto:"Aún hay esperanza para todo aquel que está entre los vivos; porque mejor es perro vivo que león muerto.",
    idea:"La esperanza es para los vivos.",
    demuestra:"Que no hay esperanza para los que ya murieron.",
    clave:"MEJOR ES PERRO VIVO QUE LEÓN MUERTO",
    concepto:"Esperanza",
    pregunta:"¿Hay esperanza para los muertos?" },
  { id:"v6", ref:"Eclesiastés 9:5,6",
    texto:"Los muertos nada saben, ni tienen más paga; porque su memoria es puesta en olvido. También su amor y su odio y su envidia fenecieron ya; y nunca más tendrán parte en todo lo que se hace debajo del sol.",
    idea:"El estado completo de los muertos.",
    demuestra:"ES EL VERSÍCULO MÁS IMPORTANTE DEL TEMA. De aquí sale casi todo.",
    clave:"LOS MUERTOS NADA SABEN",
    concepto:"Estado de los muertos",
    pregunta:"¿Qué saben los muertos?" },
  { id:"v7", ref:"Levítico 20:6,27",
    texto:"La persona que atendiere a encantadores o adivinos... yo pondré mi rostro contra la tal persona, y la cortaré de entre su pueblo. El hombre o la mujer que evocare espíritus de muertos o se entregare a la adivinación, ha de morir; serán apedreados.",
    idea:"Está prohibido consultar a los muertos.",
    demuestra:"Que Dios prohíbe la adivinación, con pena de muerte.",
    clave:"EVOCARE ESPÍRITUS DE MUERTOS… HA DE MORIR",
    concepto:"Prohibición",
    pregunta:"¿Podemos hablar con los muertos?" },
  { id:"v8", ref:"1 Samuel 28:6,7",
    texto:"Y consultó Saúl a Jehová; pero Jehová no le respondió ni por sueños, ni por Urim, ni por profetas. Entonces Saúl dijo a sus criados: Buscadme una mujer que tenga espíritu de adivinación.",
    idea:"Saúl fue donde la adivina porque Dios no le respondía.",
    demuestra:"Que ir donde la adivina no fue válido: fue desesperación tras el silencio de Dios.",
    clave:"NI POR SUEÑOS, NI POR URIM, NI POR PROFETAS",
    concepto:"Saúl y la mujer de Endor",
    pregunta:"¿Por qué Saúl fue donde la adivina?" },
  { id:"v9", ref:"2 Corintios 11:14",
    texto:"Y no es maravilla, porque el mismo Satanás se disfraza como ángel de luz.",
    idea:"Satanás puede aparecer bajo una apariencia engañosa.",
    demuestra:"Que si Satanás se disfraza, un demonio puede presentarse con la apariencia de un ser querido.",
    clave:"SE DISFRAZA COMO ÁNGEL DE LUZ",
    concepto:"Apariencia engañosa",
    pregunta:"¿Quién aparece cuando alguien dice ver a un muerto?" }
];

const MEMORIA = [
  { c:"CREACIÓN", r:"Polvo + aliento de vida = alma viviente", v:"Gén. 2:7", k:"polvo, aliento, alma viviente" },
  { c:"EL ALMA", r:"No es una parte: es el RESULTADO de unir cuerpo y espíritu", v:"Gén. 2:7", k:"resultado, unión" },
  { c:"¿MUERE EL ALMA?", r:"Sí. El alma que pecare, esa morirá", v:"Eze. 18:4", k:"pecare, morirá" },
  { c:"CUERPO SIN ESPÍRITU", r:"Nada", v:"Diagrama del material", k:"nada" },
  { c:"LOS MUERTOS", r:"Nada saben", v:"Ecl. 9:5", k:"nada saben" },
  { c:"SU MEMORIA", r:"Es puesta en olvido", v:"Ecl. 9:5", k:"memoria, olvido" },
  { c:"AMOR, ODIO, ENVIDIA", r:"Fenecieron ya", v:"Ecl. 9:6", k:"fenecieron" },
  { c:"¿PARTICIPAN?", r:"Nunca más, en nada debajo del sol", v:"Ecl. 9:6", k:"nunca más, debajo del sol" },
  { c:"¿TIENEN PAGA?", r:"No tienen más paga", v:"Ecl. 9:5", k:"sin paga" },
  { c:"LA ESPERANZA", r:"Solo para los que están entre los vivos", v:"Ecl. 9:4", k:"vivos, perro vivo" },
  { c:"JUSTO E IMPÍO", r:"Un mismo suceso ocurre a todos", v:"Ecl. 9:2", k:"mismo suceso" },
  { c:"CONSULTAR MUERTOS", r:"Prohibido. Quien lo hace ha de morir", v:"Lev. 20:27", k:"prohibido, apedreados" },
  { c:"SAÚL", r:"Dios no le respondió", v:"1 Sam. 28:6", k:"no le respondió" },
  { c:"¿CÓMO NO RESPONDIÓ?", r:"Ni por sueños, ni por Urim, ni por profetas", v:"1 Sam. 28:6", k:"sueños, Urim, profetas" },
  { c:"LA MUJER", r:"Sin nombre en la Biblia. La mujer de Endor", v:"1 Sam. 28:7", k:"sin nombre, Endor" },
  { c:"¿ERA SAMUEL?", r:"No. Fue una mujer con espíritu de adivinación", v:"1 Sam. 28:7", k:"no, adivinación" },
  { c:"SATANÁS", r:"Se disfraza como ángel de luz", v:"2 Cor. 11:14", k:"disfraza, ángel de luz" },
  { c:"LO QUE APARECE", r:"Un demonio con la apariencia de un ser querido", v:"2 Cor. 11:14", k:"demonio, apariencia" }
];

const MODULOS = [
  { id:"m1", titulo:"La creación del ser humano",
    explicacion:"Dios hizo al hombre y la mujer a su imagen, con individualidad propia y con la facultad y libertad de pensar y obrar. Los creó libres. Cada uno es una unidad indivisible de cuerpo, mente y espíritu, que depende de Dios para la vida, el aliento y todo lo demás.",
    versiculo:"Gén. 1:26-28; 2:7", recordar:"A su imagen · libres · unidad indivisible · dependen de Dios",
    practica:"¿Cómo creó Dios al hombre?", respuesta:"A su imagen, libre, como una unidad indivisible de cuerpo, mente y espíritu." },
  { id:"m2", titulo:"La fórmula de la vida",
    explicacion:"Jehová Dios formó al hombre del polvo de la tierra y sopló en su nariz aliento de vida, y fue el hombre un alma viviente. CUERPO + ESPÍRITU = ALMA VIVIENTE. Separados, no queda nada. Es igual que el agua: hidrógeno más oxígeno da agua, pero por separado no hay agua.",
    versiculo:"Gén. 2:7", recordar:"El alma no es una parte del hombre: es el RESULTADO de la unión",
    practica:"¿Qué pasa si se separan el cuerpo y el espíritu?", respuesta:"No queda nada. Igual que el hidrógeno y el oxígeno separados no son agua." },
  { id:"m3", titulo:"Lo que pasó con el pecado",
    explicacion:"Nuestros primeros padres desobedecieron a Dios, negaron su dependencia de él y cayeron de la elevada posición que ocupaban bajo su gobierno. La imagen de Dios en ellos se desfiguró y quedaron sujetos a la muerte. Sus descendientes participan de esa naturaleza caída: nacen con debilidades y tendencias hacia el mal. Pero Dios, en Cristo, restaura en los mortales penitentes la imagen de su Hacedor.",
    versiculo:"Gén. 3; Sal. 51:5; Rom. 5:12-17", recordar:"Desobedecieron → negaron dependencia → cayeron → imagen desfigurada → sujetos a muerte",
    practica:"¿Qué pasó con la imagen de Dios en el hombre?", respuesta:"Se desfiguró, y quedaron sujetos a la muerte." },
  { id:"m4", titulo:"El alma puede morir",
    explicacion:"Todas las almas son de Dios: como el alma del padre, así el alma del hijo. Y el alma que pecare, esa morirá. El justo vivirá; el que hace abominación de cierto morirá. Pero el hijo justo no morirá por la maldad de su padre.",
    versiculo:"Eze. 18:4-18", recordar:"El alma SÍ puede morir · cada quien responde por lo suyo",
    practica:"¿Es inmortal el alma?", respuesta:"No. El alma que pecare, esa morirá." },
  { id:"m5", titulo:"El estado de los muertos",
    explicacion:"Los que viven saben que han de morir, pero los muertos nada saben, ni tienen más paga, porque su memoria es puesta en olvido. También su amor y su odio y su envidia fenecieron ya, y nunca más tendrán parte en todo lo que se hace debajo del sol. Un mismo suceso ocurre al justo y al impío. Aún hay esperanza para todo aquel que está entre los vivos.",
    versiculo:"Ecl. 9:1-6", recordar:"Nada saben · sin paga · memoria en olvido · amor y odio fenecieron · nunca más parte",
    practica:"¿Los muertos saben lo que ocurre entre los vivos?", respuesta:"No. Los muertos nada saben y su memoria es puesta en olvido." },
  { id:"m6", titulo:"Prohibido consultar a los muertos",
    explicacion:"Dios pondrá su rostro contra la persona que atendiere a encantadores o adivinos, y la cortará de entre su pueblo. El hombre o la mujer que evocare espíritus de muertos o se entregare a la adivinación ha de morir: serán apedreados.",
    versiculo:"Lev. 20:6,27", recordar:"Prohibido · encantadores y adivinos · evocar espíritus · ha de morir",
    practica:"¿Qué dice Dios de quien consulta adivinos?", respuesta:"Que pondrá su rostro contra esa persona y la cortará de entre su pueblo." },
  { id:"m7", titulo:"Saúl y la mujer de Endor",
    explicacion:"Saúl consultó a Jehová, pero Jehová no le respondió ni por sueños, ni por Urim, ni por profetas. Entonces Saúl mandó a buscar una mujer que tuviera espíritu de adivinación, para preguntar por medio de ella. El material no da el nombre de esa mujer, y la Biblia tampoco: se la conoce por el lugar donde vivía, Endor.",
    versiculo:"1 Sam. 28:6,7", recordar:"Dios NO le respondió · sueños, Urim, profetas · mujer con espíritu de adivinación",
    practica:"¿Por qué Saúl buscó a la adivina?", respuesta:"Porque consultó a Jehová y Jehová no le respondió ni por sueños, ni por Urim, ni por profetas." },
  { id:"m8", titulo:"La apariencia engañosa",
    explicacion:"La Biblia advierte que Satanás puede aparecer bajo una apariencia engañosa. Pablo dice que el mismo Satanás se disfraza como ángel de luz. Si Satanás puede disfrazarse de algo que no es, no hay problema en entender que un demonio se presente con la apariencia de un ser querido.",
    versiculo:"2 Cor. 11:14", recordar:"Se disfraza como ángel de luz · la apariencia no prueba la identidad",
    practica:"Si los muertos nada saben, ¿quién aparece?", respuesta:"No es el muerto. Es un engaño: Satanás se disfraza y un demonio puede tomar la apariencia de un ser querido." }
];

const CONFUSIONES = [
  { a:"El alma", b:"Algo separado que sobrevive al morir",
    exp:"El alma es el RESULTADO de unir cuerpo y espíritu, no una pieza que se desprende. Por eso puede morir: el alma que pecare, esa morirá." },
  { a:"Morir", b:"Quedar consciente en otro lugar",
    exp:"Los muertos nada saben, su memoria es puesta en olvido y nunca más tienen parte en lo que se hace debajo del sol. No hay conciencia activa." },
  { a:"Que Saúl fuera donde la adivina", b:"Que los muertos sí hablan",
    exp:"Fue porque Dios NO le respondió, y Dios ya había prohibido esa consulta con pena de muerte. El hecho no valida la práctica." },
  { a:"La apariencia", b:"La identidad real",
    exp:"Que algo se vea como un ser querido no significa que lo sea. Satanás se disfraza como ángel de luz." },
  { a:"Un mismo suceso", b:"Un mismo destino final",
    exp:"El material dice que el justo y el impío mueren de la misma manera. Habla del hecho de morir, no del destino eterno." },
  { a:"Esperanza para los muertos", b:"Esperanza para los vivos",
    exp:"Eclesiastés 9:4 dice que la esperanza es para el que está ENTRE LOS VIVOS. Suena a trampa y lo es." }
];

const CASOS = [
  { s:"Una señora dice que su mamá fallecida se le apareció en sueños y le dio un mensaje.",
    r:"Los muertos nada saben y nunca más tienen parte en lo que se hace debajo del sol. No pudo ser su mamá. Satanás se disfraza como ángel de luz y un demonio puede presentarse con la apariencia de un ser querido.", v:"Ecl. 9:5,6; 2 Cor. 11:14" },
  { s:"Un amigo dice que fue donde una adivina solo por curiosidad, sin creer.",
    r:"Dios dice que pondrá su rostro contra la persona que atendiere a encantadores o adivinos. No hace excepción por curiosidad.", v:"Lev. 20:6" },
  { s:"Alguien argumenta: si Saúl habló con Samuel, entonces sí se puede hablar con los muertos.",
    r:"Saúl fue donde una mujer con espíritu de adivinación porque Jehová no le respondió ni por sueños, ni por Urim, ni por profetas. Y Dios ya había prohibido esa consulta.", v:"1 Sam. 28:6,7; Lev. 20:27" },
  { s:"Un joven dice que su abuelo lo cuida desde el cielo y sabe lo que hace.",
    r:"Los muertos nada saben, su memoria es puesta en olvido, y nunca más tendrán parte en todo lo que se hace debajo del sol.", v:"Ecl. 9:5,6" },
  { s:"Una persona dice que el alma es inmortal y no puede morir.",
    r:"Ezequiel 18:4 dice que el alma que pecare, esa morirá. Y el alma es el resultado de unir cuerpo y espíritu, no una parte que sobreviva.", v:"Eze. 18:4; Gén. 2:7" },
  { s:"Alguien pregunta por qué un buen cristiano murió igual que un criminal.",
    r:"Todo acontece de la misma manera a todos: un mismo suceso ocurre al justo y al impío, al bueno y al que peca.", v:"Ecl. 9:2" },
  { s:"Un familiar quiere ir a un médium para despedirse de alguien que murió.",
    r:"Está prohibido: quien evoque espíritus de muertos ha de morir. Y no hay con quién hablar, porque los muertos nada saben.", v:"Lev. 20:27; Ecl. 9:5" },
  { s:"Alguien vio una figura idéntica a su hermano muerto y quedó convencido.",
    r:"La apariencia no prueba la identidad. Satanás se disfraza como ángel de luz; un demonio puede presentarse con la apariencia de un ser querido.", v:"2 Cor. 11:14" },
  { s:"Un muchacho dice que da lo mismo cómo viva porque al final todos mueren igual.",
    r:"Es cierto que un mismo suceso ocurre a todos, pero el material también dice que el justo vivirá y que el que hace abominación de cierto morirá.", v:"Ecl. 9:2; Eze. 18:9,13" },
  { s:"Alguien pregunta si el hijo paga el pecado del padre.",
    r:"No. El hijo que ve los pecados de su padre y no hace según ellos no morirá por la maldad de su padre: de cierto vivirá.", v:"Eze. 18:14-18" },
  { s:"Una persona dice que Dios le habla por medio de una vidente.",
    r:"Dios prohíbe atender a encantadores o adivinos. Cuando Saúl buscó esa vía, fue precisamente porque Dios no le respondía.", v:"Lev. 20:6; 1 Sam. 28:6" },
  { s:"Un compañero dice que el cuerpo muere pero el espíritu sigue viviendo consciente.",
    r:"Cuerpo sin espíritu no es nada, y los muertos nada saben. El alma es el resultado de la unión, no algo que continúe aparte.", v:"Gén. 2:7; Ecl. 9:5" },
  { s:"Alguien pregunta si hay esperanza para el que ya murió.",
    r:"La esperanza es para el que está entre los vivos: mejor es perro vivo que león muerto.", v:"Ecl. 9:4" },
  { s:"Una persona sincera y creyente insiste en que habló con su madre muerta.",
    r:"La sinceridad no cambia el hecho. Los muertos nada saben; lo que se le presentó fue un engaño con apariencia de ser querido.", v:"Ecl. 9:5; 2 Cor. 11:14" },
  { s:"Alguien dice que las almas de los muertos vagan buscando descanso.",
    r:"Los muertos nada saben y nunca más tendrán parte en lo que se hace debajo del sol. Esa idea no está en el material.", v:"Ecl. 9:5,6" }
];

/* type: mc = selección múltiple · vf = verdadero/falso · open = pregunta directa (modo jurado)
   difficulty: 1 fácil · 2 normal · 3 difícil · 4 capciosa                                    */
const PREGUNTAS = [
  {id:1,cat:"creacion",type:"mc",difficulty:1,q:"¿Con qué formó Dios al hombre?",opts:["Con barro y agua","Con el polvo de la tierra","Con luz","Con su propia sustancia"],a:1,verse:"Gén. 2:7",exp:"Dios formó al hombre del polvo de la tierra.",keywords:["polvo","tierra"]},
  {id:2,cat:"creacion",type:"mc",difficulty:1,q:"¿Qué sopló Dios en su nariz?",opts:["Su espíritu eterno","Un alma inmortal","Aliento de vida","Sabiduría"],a:2,verse:"Gén. 2:7",exp:"Sopló aliento de vida.",keywords:["aliento","vida"]},
  {id:3,cat:"creacion",type:"mc",difficulty:2,q:"¿Qué FUE el hombre como resultado?",opts:["Un espíritu","Un alma viviente","Un ángel","Un ser inmortal"],a:1,verse:"Gén. 2:7",exp:"Y fue el hombre un alma viviente. No la recibió: llegó a serlo.",keywords:["alma","viviente"]},
  {id:4,cat:"creacion",type:"vf",difficulty:3,q:"El hombre RECIBIÓ un alma cuando Dios sopló.",a:false,verse:"Gén. 2:7",exp:"El hombre FUE un alma viviente. No la recibió: llegó a serlo al unirse cuerpo y aliento.",keywords:[]},
  {id:5,cat:"creacion",type:"mc",difficulty:2,q:"Según el material, el ser humano es…",opts:["Tres partes separables","Una unidad indivisible","Solo cuerpo","Solo espíritu"],a:1,verse:"En Esto Creemos",exp:"Una unidad indivisible de cuerpo, mente y espíritu.",keywords:["unidad","indivisible"]},
  {id:6,cat:"creacion",type:"mc",difficulty:2,q:"¿De qué depende el ser humano?",opts:["De sí mismo","De la naturaleza","De Dios para la vida, el aliento y todo lo demás","De sus obras"],a:2,verse:"En Esto Creemos",exp:"Depende de Dios para la vida, el aliento y todo lo demás.",keywords:["Dios","vida","aliento"]},
  {id:7,cat:"creacion",type:"vf",difficulty:2,q:"Dios creó al hombre sin libertad de elegir.",a:false,verse:"En Esto Creemos",exp:"Los creó libres, con la facultad y libertad de pensar y obrar.",keywords:[]},
  {id:8,cat:"creacion",type:"open",difficulty:2,q:"¿Cuáles son los elementos con los que Dios creó al hombre?",a:"El polvo de la tierra y el aliento de vida.",verse:"Gén. 2:7",exp:"Polvo de la tierra más aliento de vida igual a alma viviente.",keywords:["polvo","aliento"]},
  {id:9,cat:"pecado",type:"mc",difficulty:2,q:"Al desobedecer, la imagen de Dios en el hombre…",opts:["Se perdió del todo","Se desfiguró","Se mantuvo igual","Se duplicó"],a:1,verse:"En Esto Creemos",exp:"La imagen de Dios en ellos se desfiguró y quedaron sujetos a la muerte.",keywords:["desfiguró"]},
  {id:10,cat:"pecado",type:"mc",difficulty:2,q:"Los descendientes de Adán y Eva nacen…",opts:["Perfectos","Neutros","Con debilidades y tendencias hacia el mal","Sin alma"],a:2,verse:"En Esto Creemos",exp:"Nacen con debilidades y tendencias hacia el mal.",keywords:["debilidades","tendencias"]},
  {id:11,cat:"pecado",type:"mc",difficulty:2,q:"¿Quién restaura la imagen de Dios?",opts:["El hombre con esfuerzo","Dios en Cristo, por su Espíritu Santo","Los ángeles","La iglesia"],a:1,verse:"En Esto Creemos",exp:"Dios, en Cristo, restaura en los mortales penitentes la imagen de su Hacedor.",keywords:["Dios","Cristo","Espíritu"]},
  {id:12,cat:"pecado",type:"open",difficulty:2,q:"¿Qué pasó cuando nuestros primeros padres desobedecieron a Dios?",a:"Negaron su dependencia, cayeron de su posición, la imagen de Dios se desfiguró y quedaron sujetos a la muerte.",verse:"Gén. 3",exp:"Cuatro consecuencias: negaron dependencia, cayeron, imagen desfigurada, sujetos a muerte.",keywords:["desfiguró","muerte","cayeron","dependencia"]},
  {id:13,cat:"alma",type:"mc",difficulty:1,q:"Según Ezequiel 18:4, el alma que pecare…",opts:["Sufrirá","Será perdonada","Morirá","Se purificará"],a:2,verse:"Eze. 18:4",exp:"El alma que pecare, esa morirá.",keywords:["morirá"]},
  {id:14,cat:"alma",type:"vf",difficulty:3,q:"El alma es inmortal y no puede morir.",a:false,verse:"Eze. 18:4",exp:"El alma que pecare, esa morirá.",keywords:[]},
  {id:15,cat:"alma",type:"mc",difficulty:2,q:"¿De quién son todas las almas?",opts:["Del hombre","De Dios","De sus padres","De nadie"],a:1,verse:"Eze. 18:4",exp:"Todas las almas son mías, dice Jehová.",keywords:["Dios"]},
  {id:16,cat:"alma",type:"mc",difficulty:3,q:"Cuerpo sin espíritu da como resultado…",opts:["Un alma dormida","Un espíritu libre","Nada","Un fantasma"],a:2,verse:"Diagrama del material",exp:"Igual que hidrógeno y oxígeno separados: no hay agua. Cuerpo sin espíritu no es nada.",keywords:["nada"]},
  {id:17,cat:"alma",type:"vf",difficulty:3,q:"Hidrógeno y oxígeno separados siguen siendo agua.",a:false,verse:"Diagrama del material",exp:"No hay agua. Es la analogía: sin unión, no hay resultado.",keywords:[]},
  {id:18,cat:"alma",type:"mc",difficulty:2,q:"El hijo justo de un padre malvado…",opts:["Morirá igual","No morirá por la maldad de su padre","Será juzgado igual","Pagará la mitad"],a:1,verse:"Eze. 18:17",exp:"Este no morirá por la maldad de su padre; de cierto vivirá.",keywords:["no morirá","padre"]},
  {id:19,cat:"alma",type:"vf",difficulty:2,q:"El hijo muere por el pecado de su padre.",a:false,verse:"Eze. 18:17",exp:"El hijo justo no morirá por la maldad de su padre.",keywords:[]},
  {id:20,cat:"alma",type:"open",difficulty:2,q:"¿Puede morir el alma?",a:"Sí. El alma que pecare, esa morirá.",verse:"Eze. 18:4",exp:"Ezequiel 18:4 lo dice directamente.",keywords:["sí","morirá","pecare"]},
  {id:21,cat:"muertos",type:"mc",difficulty:1,q:"Según Eclesiastés 9:5, los muertos…",opts:["Saben todo","Nada saben","Saben solo lo bueno","Saben lo que pasó antes"],a:1,verse:"Ecl. 9:5",exp:"Los muertos nada saben.",keywords:["nada","saben"]},
  {id:22,cat:"muertos",type:"mc",difficulty:2,q:"¿Qué pasa con la memoria de los muertos?",opts:["Se conserva","Aumenta","Es puesta en olvido","Se transfiere"],a:2,verse:"Ecl. 9:5",exp:"Su memoria es puesta en olvido.",keywords:["olvido"]},
  {id:23,cat:"muertos",type:"mc",difficulty:2,q:"El amor, el odio y la envidia de los muertos…",opts:["Continúan","Fenecieron ya","Se intensifican","Se transforman"],a:1,verse:"Ecl. 9:6",exp:"Su amor y su odio y su envidia fenecieron ya.",keywords:["fenecieron"]},
  {id:24,cat:"muertos",type:"mc",difficulty:2,q:"¿Participan los muertos en lo que se hace debajo del sol?",opts:["Sí, siempre","Solo los justos","Nunca más","A veces"],a:2,verse:"Ecl. 9:6",exp:"Nunca más tendrán parte en todo lo que se hace debajo del sol.",keywords:["nunca más"]},
  {id:25,cat:"muertos",type:"mc",difficulty:3,q:"¿Para quién hay esperanza?",opts:["Para los muertos","Para los justos muertos","Para los que están entre los vivos","Para todos por igual"],a:2,verse:"Ecl. 9:4",exp:"Aún hay esperanza para todo aquel que está entre los vivos.",keywords:["vivos"]},
  {id:26,cat:"muertos",type:"mc",difficulty:2,q:"Completa: “Mejor es…”",opts:["león vivo que perro muerto","perro vivo que león muerto","hombre justo que impío","poco que nada"],a:1,verse:"Ecl. 9:4",exp:"Mejor es perro vivo que león muerto.",keywords:["perro vivo","león muerto"]},
  {id:27,cat:"muertos",type:"mc",difficulty:2,q:"Al justo y al impío les ocurre…",opts:["Distinto suceso","Un mismo suceso","Nada","Depende de su fe"],a:1,verse:"Ecl. 9:2",exp:"Un mismo suceso ocurre al justo y al impío.",keywords:["mismo suceso"]},
  {id:28,cat:"muertos",type:"vf",difficulty:4,q:"Hay esperanza para los que ya murieron.",a:false,verse:"Ecl. 9:4",exp:"La esperanza es para el que está ENTRE LOS VIVOS. Suena a que debe ser sí, y no lo es.",keywords:[]},
  {id:29,cat:"muertos",type:"vf",difficulty:3,q:"Los muertos todavía tienen paga.",a:false,verse:"Ecl. 9:5",exp:"Ni tienen más paga.",keywords:[]},
  {id:30,cat:"muertos",type:"open",difficulty:1,q:"¿Qué saben los muertos?",a:"Nada. Los muertos nada saben.",verse:"Ecl. 9:5",exp:"Es la frase central del tema.",keywords:["nada","saben"]},
  {id:31,cat:"muertos",type:"open",difficulty:2,q:"¿Los muertos participan en lo que ocurre debajo del sol?",a:"No. Nunca más tendrán parte en todo lo que se hace debajo del sol.",verse:"Ecl. 9:6",exp:"Es la misma enseñanza, preguntada de otra forma.",keywords:["no","nunca","parte"]},
  {id:32,cat:"muertos",type:"open",difficulty:2,q:"¿Qué enseña Eclesiastés acerca de la condición de los muertos?",a:"Que nada saben, no tienen más paga, su memoria es puesta en olvido y su amor, odio y envidia fenecieron.",verse:"Ecl. 9:5,6",exp:"Reformulación de la misma enseñanza.",keywords:["nada saben","olvido","fenecieron"]},
  {id:33,cat:"prohibicion",type:"mc",difficulty:2,q:"¿Qué hará Dios con quien atienda a adivinos?",opts:["Lo perdonará","Pondrá su rostro contra él y lo cortará de su pueblo","Lo ignorará","Lo advertirá"],a:1,verse:"Lev. 20:6",exp:"Pondré mi rostro contra la tal persona, y la cortaré de entre su pueblo.",keywords:["rostro","cortaré"]},
  {id:34,cat:"prohibicion",type:"mc",difficulty:2,q:"¿Cuál es el castigo por evocar espíritus de muertos?",opts:["Destierro","Multa","Ha de morir: serán apedreados","Ayuno"],a:2,verse:"Lev. 20:27",exp:"Ha de morir; serán apedreados; su sangre será sobre ellos.",keywords:["morir","apedreados"]},
  {id:35,cat:"prohibicion",type:"vf",difficulty:3,q:"Dios permite consultar adivinos si es por una buena causa.",a:false,verse:"Lev. 20:6",exp:"No hay excepciones. Dios pondrá su rostro contra esa persona.",keywords:[]},
  {id:36,cat:"prohibicion",type:"open",difficulty:1,q:"¿Podemos hablar con los muertos?",a:"No. Está prohibido, y además los muertos nada saben.",verse:"Lev. 20:27; Ecl. 9:5",exp:"Dos razones: la prohibición y el estado de los muertos.",keywords:["no","prohibido"]},
  {id:37,cat:"saul",type:"mc",difficulty:2,q:"¿Por cuáles medios Jehová NO respondió a Saúl?",opts:["Sueños, Urim y profetas","Ángeles y visiones","Sacerdotes y jueces","Fuego y nube"],a:0,verse:"1 Sam. 28:6",exp:"Ni por sueños, ni por Urim, ni por profetas.",keywords:["sueños","Urim","profetas"]},
  {id:38,cat:"saul",type:"mc",difficulty:2,q:"¿Qué buscó Saúl después de que Dios no le respondió?",opts:["Un profeta","Un sacerdote","Una mujer con espíritu de adivinación","Un ejército"],a:2,verse:"1 Sam. 28:7",exp:"Buscadme una mujer que tenga espíritu de adivinación.",keywords:["mujer","adivinación"]},
  {id:39,cat:"saul",type:"mc",difficulty:4,q:"¿Cómo se llamaba la mujer con la que Saúl habló?",opts:["Débora","Jezabel","La Biblia no da su nombre","Endora"],a:2,verse:"1 Sam. 28:7",exp:"No se nombra. Se la conoce como la mujer de Endor, por el lugar donde vivía.",keywords:["no","nombre","Endor"]},
  {id:40,cat:"saul",type:"vf",difficulty:4,q:"La Biblia dice que Saúl habló con el espíritu de Samuel.",a:false,verse:"1 Sam. 28:6,7",exp:"LA PREGUNTA MÁS CAPCIOSA. El material dice que fue donde una mujer con espíritu de adivinación porque Dios no le respondía.",keywords:[]},
  {id:41,cat:"saul",type:"vf",difficulty:2,q:"Saúl consultó a Jehová antes de ir donde la adivina.",a:true,verse:"1 Sam. 28:6",exp:"Consultó a Jehová, pero Jehová no le respondió.",keywords:[]},
  {id:42,cat:"saul",type:"open",difficulty:3,q:"¿Por qué no debemos creer que era el espíritu de Samuel?",a:"Porque los muertos nada saben, y porque Satanás se disfraza como ángel de luz.",verse:"Ecl. 9:5; 2 Cor. 11:14",exp:"Dos razones combinadas. Es la pregunta 12 del material.",keywords:["nada saben","disfraza","ángel de luz"]},
  {id:43,cat:"satanas",type:"mc",difficulty:1,q:"Según 2 Corintios 11:14, Satanás se disfraza como…",opts:["Serpiente","Ángel de luz","Profeta","Rey"],a:1,verse:"2 Cor. 11:14",exp:"El mismo Satanás se disfraza como ángel de luz.",keywords:["ángel","luz"]},
  {id:44,cat:"satanas",type:"mc",difficulty:3,q:"Si Satanás puede disfrazarse, entonces un demonio puede…",opts:["Resucitar a alguien","Presentarse con la apariencia de un ser querido","Leer la mente","Predecir el futuro"],a:1,verse:"2 Cor. 11:14",exp:"Es la conclusión directa del material.",keywords:["apariencia","ser querido"]},
  {id:45,cat:"satanas",type:"vf",difficulty:2,q:"Un demonio puede presentarse con la apariencia de un ser querido.",a:true,verse:"2 Cor. 11:14",exp:"Si Satanás se disfraza de algo que no es, un demonio también puede.",keywords:[]},
  {id:46,cat:"satanas",type:"open",difficulty:3,q:"¿Qué pasa con las personas que dicen haber hablado con sus seres queridos muertos?",a:"Están siendo engañadas. No es su ser querido: es un demonio con su apariencia.",verse:"Ecl. 9:5; 2 Cor. 11:14",exp:"Es la pregunta 14 del material.",keywords:["engañadas","engaño","demonio","apariencia"]},
  {id:47,cat:"satanas",type:"vf",difficulty:4,q:"Si alguien es sincero y creyente, lo que vio sí pudo ser su familiar muerto.",a:false,verse:"Ecl. 9:5",exp:"La sinceridad no cambia el hecho. Los muertos nada saben.",keywords:[]},
  {id:48,cat:"muertos",type:"open",difficulty:2,q:"¿Hay esperanza para los muertos?",a:"No. La esperanza es para los que están entre los vivos.",verse:"Ecl. 9:4",exp:"Pregunta 8 del material. Es capciosa: suena a que debe ser sí.",keywords:["no","vivos"]},
  {id:49,cat:"muertos",type:"open",difficulty:2,q:"¿Podemos ver el espíritu de los muertos?",a:"No. Lo que se ve no es el muerto: es un engaño.",verse:"Ecl. 9:5,6; 2 Cor. 11:14",exp:"Pregunta 9 del material.",keywords:["no","engaño"]},
  {id:50,cat:"muertos",type:"open",difficulty:2,q:"¿El justo y el injusto mueren de la misma manera?",a:"Sí. Un mismo suceso ocurre al justo y al impío.",verse:"Ecl. 9:2",exp:"Pregunta 6 del material.",keywords:["sí","mismo suceso"]},
  {id:51,cat:"alma",type:"open",difficulty:2,q:"Cuando las personas mueren, ¿qué pasa con el alma?",a:"Muere. El alma que pecare, esa morirá.",verse:"Eze. 18:4",exp:"Preguntas 4 y 7 del material: aparecen dos veces, son la misma.",keywords:["muere","morirá"]},
  {id:52,cat:"alma",type:"open",difficulty:3,q:"¿Qué quiso decir Dios cuando dijo que todas las almas son suyas?",a:"Que todas le pertenecen por igual y cada una responde por sí misma.",verse:"Eze. 18:4",exp:"Pregunta 5 del material. En el PDF está cortada: dice “son del” y debe decir “son mías”.",keywords:["pertenecen","responde"]},
  {id:53,cat:"creacion",type:"open",difficulty:1,q:"¿Cómo creó Dios al hombre?",a:"A su imagen, libre, como una unidad indivisible de cuerpo, mente y espíritu.",verse:"Gén. 1:26-28",exp:"Pregunta 1 del material.",keywords:["imagen","unidad","indivisible"]},
  {id:54,cat:"muertos",type:"mc",difficulty:4,q:"¿Cuál de estas afirmaciones SÍ está en el material?",opts:["Las almas vagan buscando descanso","Los muertos nada saben","Los muertos ven a sus familiares","Los justos muertos sí saben"],a:1,verse:"Ecl. 9:5",exp:"Las otras tres no aparecen en el material.",keywords:["nada saben"]},
  {id:55,cat:"saul",type:"mc",difficulty:4,q:"¿Cuál fue el ORDEN de lo que hizo Saúl?",opts:["Buscó la adivina y después consultó a Jehová","Consultó a Jehová, no le respondió, y después buscó la adivina","Solo buscó la adivina","Consultó a un profeta primero"],a:1,verse:"1 Sam. 28:6,7",exp:"Primero consultó a Jehová. Como no le respondió, entonces buscó la adivina.",keywords:["consultó","después"]},
  {id:56,cat:"alma",type:"vf",difficulty:3,q:"Todas las almas pertenecen a Dios.",a:true,verse:"Eze. 18:4",exp:"Como el alma del padre, así el alma del hijo es mía.",keywords:[]},
  {id:57,cat:"muertos",type:"vf",difficulty:2,q:"Los muertos saben lo que ocurre entre los vivos.",a:false,verse:"Ecl. 9:5",exp:"Los muertos nada saben.",keywords:[]},
  {id:58,cat:"muertos",type:"vf",difficulty:2,q:"La memoria de los muertos permanece activa.",a:false,verse:"Ecl. 9:5",exp:"Su memoria es puesta en olvido.",keywords:[]},
  {id:59,cat:"prohibicion",type:"vf",difficulty:2,q:"Quien evoca espíritus de muertos ha de morir.",a:true,verse:"Lev. 20:27",exp:"Serán apedreados; su sangre será sobre ellos.",keywords:[]},
  {id:60,cat:"saul",type:"vf",difficulty:3,q:"Jehová le respondió a Saúl por medio de profetas.",a:false,verse:"1 Sam. 28:6",exp:"No le respondió ni por sueños, ni por Urim, ni por profetas.",keywords:[]},
  {id:61,cat:"saul",type:"vf",difficulty:3,q:"La Biblia da el nombre de la mujer de Endor.",a:false,verse:"1 Sam. 28:7",exp:"No lo da. Se la conoce por el lugar donde vivía.",keywords:[]},
  {id:62,cat:"satanas",type:"vf",difficulty:1,q:"Satanás puede disfrazarse como ángel de luz.",a:true,verse:"2 Cor. 11:14",exp:"Lo dice Pablo.",keywords:[]},
  {id:63,cat:"pecado",type:"vf",difficulty:2,q:"Al desobedecer, la imagen de Dios se desfiguró.",a:true,verse:"En Esto Creemos",exp:"Y quedaron sujetos a la muerte.",keywords:[]},
  {id:64,cat:"pecado",type:"vf",difficulty:2,q:"Los descendientes nacen sin tendencias al mal.",a:false,verse:"En Esto Creemos",exp:"Nacen con debilidades y tendencias hacia el mal.",keywords:[]},
  {id:65,cat:"pecado",type:"vf",difficulty:2,q:"Dios restaura su imagen en los mortales penitentes.",a:true,verse:"En Esto Creemos",exp:"Por medio de su Espíritu Santo.",keywords:[]},
  {id:66,cat:"creacion",type:"vf",difficulty:2,q:"El ser humano es una unidad indivisible.",a:true,verse:"En Esto Creemos",exp:"De cuerpo, mente y espíritu.",keywords:[]},
  {id:67,cat:"muertos",type:"mc",difficulty:3,q:"¿Qué NO dice el material sobre los muertos?",opts:["Que nada saben","Que su memoria es puesta en olvido","Que vagan buscando descanso","Que su amor y odio fenecieron"],a:2,verse:"Ecl. 9:5,6",exp:"Esa idea no aparece en el material.",keywords:[]},
  {id:68,cat:"alma",type:"mc",difficulty:3,q:"La analogía del agua enseña que…",opts:["El alma es como el agua","Sin unión no hay resultado","El agua es vida","El espíritu es líquido"],a:1,verse:"Diagrama del material",exp:"H + O = agua. Separados, no hay agua. Igual con cuerpo y espíritu.",keywords:["unión","resultado"]},
  {id:69,cat:"prohibicion",type:"mc",difficulty:3,q:"Dios se pone contra quien…",opts:["Duda de él","Atendiere a encantadores o adivinos","Se enoja","Llora por sus muertos"],a:1,verse:"Lev. 20:6",exp:"La persona que atendiere a encantadores o adivinos.",keywords:["encantadores","adivinos"]},
  {id:70,cat:"satanas",type:"mc",difficulty:4,q:"¿Qué prueba que una aparición es realmente un ser querido?",opts:["Que se vea igual","Que hable igual","Que sepa cosas privadas","Nada: la apariencia no prueba la identidad"],a:3,verse:"2 Cor. 11:14",exp:"Satanás se disfraza. La apariencia no prueba quién es.",keywords:["nada","apariencia"]},
  {id:71,cat:"muertos",type:"open",difficulty:3,q:"Según el material, ¿tienen los muertos conciencia de lo que ocurre?",a:"No. Nada saben y nunca más tienen parte en lo que se hace debajo del sol.",verse:"Ecl. 9:5,6",exp:"Reformulación. La respuesta sigue siendo la misma.",keywords:["no","nada saben"]},
  {id:72,cat:"alma",type:"open",difficulty:3,q:"¿Es el alma una parte del ser humano que sobrevive al morir?",a:"No. El alma es el resultado de unir cuerpo y espíritu, y puede morir.",verse:"Gén. 2:7; Eze. 18:4",exp:"Pregunta reformulada para detectar si confundes el concepto.",keywords:["no","resultado","morir"]},
  {id:73,cat:"creacion",type:"mc",difficulty:2,q:"Dios hizo al hombre y la mujer…",opts:["Por accidente","A su imagen","Iguales a los ángeles","Sin propósito"],a:1,verse:"Gén. 1:26-28",exp:"A su imagen, con individualidad propia.",keywords:["imagen"]},
  {id:74,cat:"prohibicion",type:"open",difficulty:2,q:"¿Qué dice Dios sobre consultar a los muertos?",a:"Que está prohibido: quien evoque espíritus de muertos o se entregue a la adivinación ha de morir.",verse:"Lev. 20:27",exp:"Pregunta 10 del material.",keywords:["prohibido","morir"]},
  {id:75,cat:"saul",type:"open",difficulty:2,q:"¿Qué le pasó a Saúl cuando consultó a Jehová?",a:"Jehová no le respondió ni por sueños, ni por Urim, ni por profetas.",verse:"1 Sam. 28:6",exp:"Los tres medios son pregunta de examen segura.",keywords:["no le respondió","sueños","Urim","profetas"]},
  {id:76,cat:"muertos",type:"mc",difficulty:2,q:"Completa: “Los muertos nada saben, ni tienen más…”",opts:["fuerza","paga","memoria","tiempo"],a:1,verse:"Ecl. 9:5",exp:"Ni tienen más paga.",keywords:["paga"]},
  {id:77,cat:"muertos",type:"mc",difficulty:3,q:"¿Cuántas cosas dice Eclesiastés 9:6 que fenecieron?",opts:["Dos","Tres","Cuatro","Una"],a:1,verse:"Ecl. 9:6",exp:"Tres: su amor, su odio y su envidia.",keywords:["tres"]},
  {id:78,cat:"alma",type:"mc",difficulty:3,q:"Ezequiel 18 enseña principalmente que…",opts:["Todos morirán igual","Cada quien responde por sus propios actos","El alma es eterna","Los padres pagan por los hijos"],a:1,verse:"Eze. 18:4-18",exp:"Nadie muere por el pecado de otro.",keywords:["cada quien","responde"]},
  {id:79,cat:"satanas",type:"open",difficulty:3,q:"¿Por qué la apariencia de un muerto no puede ser el muerto?",a:"Porque los muertos nada saben. Lo que aparece es Satanás disfrazado o un demonio con esa apariencia.",verse:"Ecl. 9:5; 2 Cor. 11:14",exp:"Es la lógica completa del material.",keywords:["nada saben","disfrazado","demonio"]},
  {id:80,cat:"creacion",type:"vf",difficulty:3,q:"El cuerpo y el espíritu del hombre pueden separarse y cada uno sigue siendo un ser completo.",a:false,verse:"Gén. 2:7",exp:"Cuerpo sin espíritu es nada. Es una unidad indivisible.",keywords:[]}
];

const REFORMULACIONES = {
  muertos:["¿Qué sucede con los muertos?","¿Los muertos saben lo que ocurre?","¿Qué enseña Eclesiastés sobre los muertos?","¿Tienen los muertos participación en lo que ocurre debajo del sol?","Según el material, ¿tienen conciencia los muertos?"],
  alma:["¿Puede morir el alma?","¿Es inmortal el alma?","¿Qué pasa con el alma al morir?","¿Qué dice Ezequiel 18:4 sobre el alma?"],
  saul:["¿Saúl habló con Samuel?","¿Por qué Saúl fue donde la adivina?","¿Qué pasó cuando Saúl consultó a Jehová?","¿Debemos creer que era el espíritu de Samuel?"]
};
